import { useEffect, useState } from "react";
import { Loader2, Plus, Trash2, X } from "lucide-react";
import api from "@/shared/lib/api";

const unwrap = (r: any) => r?.data?.data ?? r?.data;
const list = (r: any) => { const d = unwrap(r); return Array.isArray(d) ? d : d?.data || []; };
const errorMessage = (e: any) => e?.response?.data?.error?.message || e?.response?.data?.message || "Não foi possível concluir a operação.";

export function ManualDeliveryOrderModal({ lojaId, onClose, onCreated }: { lojaId: string; onClose: () => void; onCreated: () => void }) {
  const [step, setStep] = useState(1); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [customers, setCustomers] = useState<any[]>([]); const [query, setQuery] = useState(""); const [customer, setCustomer] = useState<any>(null);
  const [quick, setQuick] = useState({ nome: "", telefone: "" }); const [products, setProducts] = useState<any[]>([]); const [lines, setLines] = useState<any[]>([]);
  const [configuring, setConfiguring] = useState<any>(null); const [selectedVariation, setSelectedVariation] = useState(""); const [selectedOptions, setSelectedOptions] = useState<any[]>([]);
  const [address, setAddress] = useState<any>({ rua:"", numero:"", bairro:"", cidade:"", estado:"", cep:"", complemento:"" });
  const [payment, setPayment] = useState("dinheiro"); const [semTroco, setSemTroco] = useState(true); const [trocoPara, setTrocoPara] = useState("");
  useEffect(() => { api.get("/produtos_loja", { params:{ ativo:true, per_page:100 } }).then(r => setProducts(list(r))).catch(() => setError("Não foi possível carregar o catálogo.")); }, []);
  useEffect(() => { if (!query.trim()) return setCustomers([]); const t = setTimeout(() => api.get("/pedidos/admin-delivery/contacts", { params:{ busca:query } }).then(r => setCustomers(list(r))).catch(() => {}), 250); return () => clearTimeout(t); }, [query]);
  const addProduct = async (p:any) => { setError(""); if (p.modo_compra !== "configuravel") { setLines(v => [...v, { client_line_id: crypto.randomUUID(), produto_loja_id:p.id, quantidade:1, selecoes:[], nome:p.nome, preco:p.preco ?? p.preco_promocional ?? 0 }]); return; } try { const config = unwrap(await api.get(`/produtos_loja/${p.id}/configuracao`)); setConfiguring(config); setSelectedVariation(config?.variacoes?.[0]?.id || ""); setSelectedOptions([]); } catch(e) { setError(errorMessage(e)); } };
  const toggleOption = (group:any, option:any) => setSelectedOptions(current => { const exists = current.some(s => s.grupo_id === group.id && s.opcao_id === option.id); if (exists) return current.filter(s => !(s.grupo_id === group.id && s.opcao_id === option.id)); const groupItems = current.filter(s => s.grupo_id === group.id); if (group.tipo_selecao === "unica") return [...current.filter(s => s.grupo_id !== group.id), { grupo_id:group.id, opcao_id:option.id, quantidade:1 }]; const max = Number(group.maximo_selecoes || 99); return groupItems.length >= max ? current : [...current, { grupo_id:group.id, opcao_id:option.id, quantidade:1 }]; });
  const saveConfiguredLine = () => { const product = configuring?.produto; if (!product) return; const variationRequired = configuring?.variacoes?.length > 0; if (variationRequired && !selectedVariation) return setError("Selecione uma variação."); for (const group of configuring?.grupos || []) { const count = selectedOptions.filter(s => s.grupo_id === group.id).length; if (count < Number(group.minimo_selecoes || 0)) return setError(`Selecione ao menos ${group.minimo_selecoes} opção(ões) em ${group.nome}.`); } setLines(v => [...v, { client_line_id:crypto.randomUUID(), produto_loja_id:product.id, variacao_produto_loja_id:selectedVariation || null, quantidade:1, selecoes:selectedOptions, nome:product.nome, preco:product.preco }]); setConfiguring(null); };
  const createCustomer = async () => { setCustomer({ id: `quick-${Date.now()}`, ...quick, rapido: true }); setStep(2); };
  const submit = async () => { if (!customer || !lines.length) return; setBusy(true); setError(""); try {
    const geo = unwrap(await api.post("/geocoding", { street:address.rua, number:address.numero, neighborhood:address.bairro, city:address.cidade, state:address.estado, zipCode:address.cep, complement:address.complement, tenantId:lojaId, customerId:customer.id }));
    await api.post("/pedidos/admin-delivery", { contato:{ nome:customer.nome, telefone:customer.telefone }, itens:lines.map(({ nome, preco, ...line }) => line), endereco:{ ...address, latitude:geo.latitude, longitude:geo.longitude, geocoding_provider:"google", geocoding_source:"manual_address", formatted_address:geo.formatted_address, google_place_id:geo.place_id }, pagamento:{ forma_pagamento:payment, sem_troco:semTroco, troco_para:semTroco ? undefined : Number(trocoPara) } });
    onCreated(); onClose();
  } catch(e) { setError(errorMessage(e)); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-bold">Criar pedido delivery</h2><p className="text-sm text-gray-500">Etapa {step} de 4</p></div><button onClick={onClose}><X /></button></div>{error && <div className="mb-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  {step===1 && <div className="space-y-3"><input className="w-full rounded border p-2" placeholder="Buscar cliente por nome ou telefone" value={query} onChange={e=>setQuery(e.target.value)} />{customers.map(c=><button key={c.id} onClick={()=>{setCustomer(c);setStep(2)}} className="block w-full rounded border p-3 text-left"><b>{c.nome}</b><span className="ml-2 text-sm text-gray-500">{c.telefone}</span></button>)}<div className="border-t pt-4"><b>Novo cliente</b><div className="mt-2 grid gap-2 md:grid-cols-2"><input className="rounded border p-2" placeholder="Nome" value={quick.nome} onChange={e=>setQuick({...quick,nome:e.target.value})}/><input className="rounded border p-2" placeholder="Telefone" value={quick.telefone} onChange={e=>setQuick({...quick,telefone:e.target.value})}/></div><button disabled={!quick.nome||!quick.telefone||busy} onClick={createCustomer} className="mt-3 rounded bg-blue-600 px-4 py-2 text-white">Cadastrar e continuar</button></div></div>}
  {step===2 && <div><p className="mb-3 text-sm">Cliente: <b>{customer?.nome}</b></p><div className="max-h-48 overflow-auto rounded border">{products.map(p=><button key={p.id} onClick={()=>addProduct(p)} className="flex w-full justify-between border-b p-2 text-left hover:bg-gray-50"><span>{p.nome}{p.modo_compra==='configuravel'?' · configurável':''}</span><Plus className="h-4"/></button>)}</div>{configuring&&<div className="mt-3 rounded border-2 border-blue-200 p-3"><div className="flex justify-between"><b>Configurar {configuring.produto?.nome}</b><button onClick={()=>setConfiguring(null)}><X className="h-4"/></button></div>{(configuring.variacoes||[]).length>0&&<label className="mt-3 block text-sm">Variação<select className="ml-2 border p-1" value={selectedVariation} onChange={e=>setSelectedVariation(e.target.value)}>{configuring.variacoes.map((v:any)=><option key={v.id} value={v.id}>{v.nome}</option>)}</select></label>}{(configuring.grupos||[]).map((g:any)=><div key={g.id} className="mt-3"><p className="text-sm font-semibold">{g.nome} <span className="font-normal text-gray-500">({g.minimo_selecoes}-{g.maximo_selecoes})</span></p><div className="mt-1 flex flex-wrap gap-2">{(g.opcoes||[]).map((o:any)=>{const checked=selectedOptions.some(s=>s.grupo_id===g.id&&s.opcao_id===o.id);return <label key={o.id} className={`cursor-pointer rounded border px-2 py-1 text-sm ${checked?'border-blue-600 bg-blue-50':''}`}><input className="mr-1" type={g.tipo_selecao==='unica'?'radio':'checkbox'} checked={checked} onChange={()=>toggleOption(g,o)}/>{o.nome}</label>})}</div></div>)}<button onClick={saveConfiguredLine} className="mt-4 rounded bg-blue-600 px-3 py-2 text-white">Adicionar configurado</button></div>}<div className="mt-3 space-y-2">{lines.map((l,i)=><div key={l.client_line_id} className="flex items-center gap-2 rounded border p-2"><span className="flex-1">{l.nome}{l.selecoes.length?` · ${l.selecoes.length} opção(ões)`:''}</span><input className="w-16 border p-1" type="number" min="1" value={l.quantidade} onChange={e=>setLines(lines.map((x,n)=>n===i?{...x,quantidade:Number(e.target.value)}:x))}/><button onClick={()=>setLines(lines.filter((_,n)=>n!==i))}><Trash2 className="h-4 text-red-600"/></button></div>)}</div><button disabled={!lines.length} onClick={()=>setStep(3)} className="mt-4 rounded bg-blue-600 px-4 py-2 text-white">Continuar</button></div>}
  {step===3 && <div className="grid gap-2 md:grid-cols-2">{Object.entries(address).map(([k,v])=><input key={k} className="rounded border p-2" placeholder={k.replace('_',' ')} value={v as string} onChange={e=>setAddress({...address,[k]:e.target.value})}/>) }<button disabled={!address.rua||!address.numero||!address.bairro||!address.cidade||!address.estado} onClick={()=>setStep(4)} className="mt-3 rounded bg-blue-600 px-4 py-2 text-white">Continuar</button></div>}
  {step===4 && <div className="space-y-3"><label className="block">Forma de pagamento<select className="ml-2 border p-2" value={payment} onChange={e=>setPayment(e.target.value)}><option value="dinheiro">Dinheiro na entrega</option></select></label><label className="flex gap-2"><input type="checkbox" checked={semTroco} onChange={e=>setSemTroco(e.target.checked)}/> Não precisa de troco</label>{!semTroco&&<input className="border p-2" placeholder="Troco para R$" value={trocoPara} onChange={e=>setTrocoPara(e.target.value)}/>}<button disabled={busy} onClick={submit} className="rounded bg-green-600 px-4 py-2 text-white">{busy?<Loader2 className="animate-spin"/>:"Criar pedido"}</button></div>}</div></div>
}
